#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD0_PER_KEY
#define QUICK_TAP_TERM 120
#define QUICK_TAP_TERM_PER_KEY
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
